# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
      - ".github/workflows/ci-cd.yml"
      - "e2e/**"
      - "!**/*.md"
      - "!**/*.gitignore"
      - "!**/docker-compose.yml"

jobs:
  build-ui:
    name: Build and Test UI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/ui
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.20.0
      - name: Install pnpm
        run: npm install -g pnpm@10.18.1
      - name: Install UI dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint UI
        run: pnpm run lint
      - name: Test UI
        run: pnpm run test
      - name: Build UI
        run: pnpm run build

  build-backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.300
      - name: Restore dependencies
        run: dotnet restore
      - name: Build all src and tests projects
        run: dotnet build --no-restore
      - name: Test API
        run: dotnet test ./api/tests --no-build --verbosity normal
      - name: Test Email Worker
        run: dotnet test ./email-worker/tests --no-build --verbosity normal
      - name: Test Sms Worker
        run: dotnet test ./sms-worker/tests --no-build --verbosity normal

  deploy-development:
    name: Deploy to Development Environment
    runs-on: ubuntu-latest
    needs: [build-ui, build-backend]
    environment: development
    if: github.ref == 'refs/heads/main'
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Railway CLI
        run: npm install -g @railway/cli
      - name: Deploy UI
        run: |
          sed -i "s|\${API_BACKEND_HOST}|${{ vars.API_BACKEND_HOST }}|g" nginx.conf.template
          railway up --service=${{ secrets.RAILWAY_UI_SERVICE_ID }} -c
        working-directory: ./app/ui
      - name: Deploy API
        run: railway up --service=${{ secrets.RAILWAY_API_SERVICE_ID }} -c
        working-directory: ./app/api/src
      - name: Deploy Email Worker
        run: railway up --service=${{ secrets.RAILWAY_EMAIL_WORKER_SERVICE_ID }} -c
        working-directory: ./app/email-worker/src
      - name: Deploy Sms Worker
        run: railway up --service=${{ secrets.RAILWAY_SMS_WORKER_SERVICE_ID }} -c
        working-directory: ./app/sms-worker/src

  e2e-test:
    name: Run Playwright E2E Tests
    runs-on: ubuntu-latest
    needs: deploy-development
    timeout-minutes: 60
    environment: development
    env:
        E2E_BASE_URL: ${{ vars.E2E_BASE_URL }}
        CI: true
    defaults:
      run:
        working-directory: e2e
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g pnpm@10.18.1 && pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: pnpm exec playwright install chromium --with-deps
      - name: Run Playwright tests
        run: pnpm test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30

  deploy-production:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    needs: e2e-test
    environment: production
    if: github.ref == 'refs/heads/main'
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Railway CLI
        run: npm install -g @railway/cli
      - name: Deploy UI
        run: |
          sed -i "s|\${API_BACKEND_HOST}|${{ vars.API_BACKEND_HOST }}|g" nginx.conf.template
          railway up --service=${{ secrets.RAILWAY_UI_SERVICE_ID }} -c
        working-directory: ./app/ui
      - name: Deploy API
        run: railway up --service=${{ secrets.RAILWAY_API_SERVICE_ID }} -c
        working-directory: ./app/api/src
      - name: Deploy Email Worker
        run: railway up --service=${{ secrets.RAILWAY_EMAIL_WORKER_SERVICE_ID }} -c
        working-directory: ./app/email-worker/src
      - name: Deploy Sms Worker
        run: railway up --service=${{ secrets.RAILWAY_SMS_WORKER_SERVICE_ID }} -c
        working-directory: ./app/sms-worker/src