# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
      - ".github/workflows/main.yml"
      - "!**/*.md"
      - "!**/*.gitignore"
      - "!**/docker-compose.yml"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.300
      - name: Restore dependencies
        run: dotnet restore
      - name: Build all src and tests projects
        run: dotnet build --no-restore
      - name: Test API
        run: dotnet test ./api/tests --no-build --verbosity normal
      - name: Test Email Worker
        run: dotnet test ./email-worker/tests --no-build --verbosity normal
      - name: Test Sms Worker
        run: dotnet test ./sms-worker/tests --no-build --verbosity normal

  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: build
    environment: development
    if: github.ref == 'refs/heads/main'
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Railway CLI
        run: npm install -g @railway/cli
      - name: Deploy API
        run: railway up --service=${{ secrets.RAILWAY_API_SERVICE_ID }} -c
        working-directory: ./app/api/src
      - name: Deploy Email Worker
        run: railway up --service=${{ secrets.RAILWAY_EMAIL_WORKER_SERVICE_ID }} -c
        working-directory: ./app/email-worker/src
      - name: Deploy Sms Worker
        run: railway up --service=${{ secrets.RAILWAY_SMS_WORKER_SERVICE_ID }} -c
        working-directory: ./app/sms-worker/src
      