# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
      - ".github/workflows/main.yml"
      - "!**/*.md"
      - "!**/*.gitignore"
      - "!**/docker-compose.yml"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.300
      - name: Restore dependencies
        run: dotnet restore
      - name: Build API
        run: dotnet build ./api/src --no-restore
      - name: Test API
        run: dotnet test ./api/tests --no-build --verbosity normal
      - name: Build Email Worker
        run: dotnet build ./email-worker/src --no-restore
      - name: Test Email Worker
        run: dotnet test ./email-worker/tests --no-build --verbosity normal
      - name: Build Sms Worker
        run: dotnet build ./sms-worker/src --no-restore
      - name: Test Sms Worker
        run: dotnet test ./sms-worker/tests --no-build --verbosity normal
