name: RabbitMQ

on:
  push:
    branches: [ "main" ]
    paths:
      - "rabbitmq/**"
      - ".github/workflows/rabbitmq.yml"

jobs:
  deploy:
    name: Deploy RabbitMQ
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    environment: development
    if: github.ref == 'refs/heads/main'
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy RabbitMQ
        run: railway up --service=${{ secrets.RAILWAY_RABBITMQ_SERVICE_ID }} -c
        working-directory: ./rabbitmq
